language: php

php:
  - 8.1

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 8.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - composer test
